

- type: entity
  suffix: Средневековье
  name: яблоко
  parent: FoodProduceBase
  id: FoodMedievalApple
  description: Сочное и сладкое яблоко, символ изобилия.
  components:
  - type: StaticPrice
    price: 14.5
  - type: FlavorProfile
    flavors:
      - apple
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 10
        reagents:
        - ReagentId: Nutriment
          Quantity: 3
        - ReagentId: Vitamin
          Quantity: 2
  - type: Sprite
    sprite: _DeadSpace/_Medieval/Objects/Materials/Seeds/apple.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: MedievalApple
  - type: Damageable
    damageContainer: Biological
  - type: Tag
    tags:
    - Fruit
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 50
      behaviors:
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
      - !type:SpawnEntitiesBehavior
        spawn:
          MedievalAppleSeeds:
            min: 1
            max: 2

- type: entity
  suffix: Средневековье
  name: капуста
  parent: FoodProduceBase
  id: FoodMedievalCabbage
  description: Круглый кочан капусты, полезный и хрустящий.
  components:
  - type: StaticPrice
    price: 9
  - type: FlavorProfile
    flavors:
      - cabbage
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 12
        reagents:
        - ReagentId: Nutriment
          Quantity: 5
  - type: Sprite
    sprite: _DeadSpace/_Medieval/Objects/Materials/Seeds/cabbage.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: MedievalCabbage
  - type: Damageable
    damageContainer: Biological
  - type: Tag
    tags:
    - Vegetable
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 50
      behaviors:
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
      - !type:SpawnEntitiesBehavior
        spawn:
          MedievalCabbageSeeds:
            min: 1
            max: 2

- type: entity
  suffix: Средневековье
  name: ягоды
  parent: FoodProduceBase
  id: FoodMedievalBerries
  description: Горсть лесных ягод, сладких и ароматных.
  components:
  - type: StaticPrice
    price: 14
  - type: FlavorProfile
    flavors:
      - berry
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 10
        reagents:
        - ReagentId: Sugar
          Quantity: 5
        - ReagentId: Nutriment
          Quantity: 2
  - type: Sprite
    sprite: _DeadSpace/_Medieval/Objects/Materials/Seeds/berries.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: MedievalBerries
  - type: Damageable
    damageContainer: Biological
  - type: Tag
    tags:
    - Fruit
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 50
      behaviors:
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
      - !type:SpawnEntitiesBehavior
        spawn:
          MedievalBerriesSeeds:
            min: 1
            max: 2

- type: entity
  suffix: Средневековье
  name: морковь
  parent: FoodProduceBase
  id: FoodMedievalCarrot
  description: Ярко-оранжевая морковь, полезна для глаз.
  components:
  - type: StaticPrice
    price: 7
  - type: FlavorProfile
    flavors:
      - carrot
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 10
        reagents:
        - ReagentId: JuiceCarrot
          Quantity: 4
        - ReagentId: Vitamin
          Quantity: 2
  - type: Sprite
    sprite: _DeadSpace/_Medieval/Objects/Materials/Seeds/carrot.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: MedievalCarrot
  - type: Damageable
    damageContainer: Biological
  - type: Tag
    tags:
    - Vegetable
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 50
      behaviors:
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
      - !type:SpawnEntitiesBehavior
        spawn:
          MedievalCarrotSeeds:
            min: 1
            max: 2

- type: entity
  suffix: Средневековье
  name: вишня
  parent: FoodProduceBase
  id: FoodMedievalCherry
  description: Кисло-сладкая вишня, любимое лакомство летом.
  components:
  - type: StaticPrice
    price: 13.6
  - type: FlavorProfile
    flavors:
      - cherry
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 10
        reagents:
        - ReagentId: Nutriment
          Quantity: 2
        - ReagentId: Sugar
          Quantity: 4
  - type: Sprite
    sprite: _DeadSpace/_Medieval/Objects/Materials/Seeds/cherry.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: MedievalCherry
  - type: Damageable
    damageContainer: Biological
  - type: Tag
    tags:
    - Fruit
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 50
      behaviors:
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
      - !type:SpawnEntitiesBehavior
        spawn:
          MedievalCherrySeeds:
            min: 1
            max: 2

- type: entity
  suffix: Средневековье
  name: лён
  parent: FoodProduceBase
  id: FoodMedievalFlax
  description: Стебель льна, из которого можно сделать нить.
  components:
  - type: Stack
    stackType: MedievalRawCloth
  - type: FlavorProfile
    flavors:
      - cotton
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 8
        reagents:
        - ReagentId: Fiber
          Quantity: 4
  - type: Sprite
    sprite: _DeadSpace/_Medieval/Objects/Materials/Seeds/flax.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: MedievalFlax
  - type: Damageable
    damageContainer: Biological
  - type: Tag
    tags:
    - MedievalFlax
    - MedievalLoomMaterialStorage
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 50
      behaviors:
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
      - !type:SpawnEntitiesBehavior
        spawn:
          MedievalFlaxSeeds:
            min: 1
            max: 2
  - type: PhysicalComposition
    materialComposition:
      MedievalRawCloth: 100

- type: entity
  id: FoodMedievalFlax5
  suffix: Средневековье, 5
  parent: FoodMedievalFlax
  components:
  - type: Stack
    count: 5

- type: entity
  suffix: Средневековье
  name: картошка
  parent: FoodProduceBase
  id: FoodMedievalPotato
  description: Сытный клубень картофеля, основа крестьянского стола.
  components:
  - type: StaticPrice
    price: 12.7
  - type: FlavorProfile
    flavors:
      - potato
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 12
        reagents:
        - ReagentId: Nutriment
          Quantity: 4
  - type: Sprite
    sprite: _DeadSpace/_Medieval/Objects/Materials/Seeds/potato.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: MedievalPotato
  - type: Damageable
    damageContainer: Biological
  - type: Tag
    tags:
    - Vegetable
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 50
      behaviors:
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
      - !type:SpawnEntitiesBehavior
        spawn:
          MedievalPotatoSeeds:
            min: 1
            max: 2

- type: entity
  suffix: Средневековье
  name: помидор
  parent: FoodProduceBase
  id: FoodMedievalTomato
  description: Сочный красный помидор, хорош как свежим, так и в рагу.
  components:
  - type: StaticPrice
    price: 9
  - type: FlavorProfile
    flavors:
      - tomato
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 10
        reagents:
        - ReagentId: Nutriment
          Quantity: 3
        - ReagentId: Vitamin
          Quantity: 1
  - type: Sprite
    sprite: _DeadSpace/_Medieval/Objects/Materials/Seeds/tomato.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: MedievalTomato
  - type: Damageable
    damageContainer: Biological
  - type: Tag
    tags:
    - Vegetable
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 50
      behaviors:
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
      - !type:SpawnEntitiesBehavior
        spawn:
          MedievalTomatoSeeds:
            min: 1
            max: 2

- type: entity
  suffix: Средневековье
  name: пшеница
  parent: FoodProduceBase
  id: FoodMedievalWheat
  description: Золотистые колосья пшеницы, источник муки и хлеба.
  components:
  - type: StaticPrice
    price: 7
  - type: FlavorProfile
    flavors:
      - wheat
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 10
        reagents:
        - ReagentId: Flour
          Quantity: 5
  - type: Sprite
    sprite: _DeadSpace/_Medieval/Objects/Materials/Seeds/wheat.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: MedievalWheat
  - type: Damageable
    damageContainer: Biological
  - type: Tag
    tags:
    - Wheat
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 50
      behaviors:
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
      - !type:SpawnEntitiesBehavior
        spawn:
          MedievalWheatSeeds:
            min: 1
            max: 2
