# Base
- type: latheRecipe
  abstract: true
  id: MedievalRawProcessingRecipe
  categories:
  - MedievalRawProcessingCategory
  completetime: 10

- type: latheRecipe
  abstract: true
  id: MedievalMaterialProcessingRecipe
  categories:
  - MedievalMaterialProcessingCategory
  completetime: 10

- type: latheRecipe
  abstract: true
  id: MedievalBaseToolsRecipe
  completetime: 10
  categories:
  - MedievalToolsCategory

- type: latheRecipe
  abstract: true
  id: MedievalBaseTileRecipe
  completetime: 10
  materials:
    MedievalProcessedWood: 100
  categories:
  - MedievalTileCategory

- type: latheRecipe
  abstract: true
  id: MedievalBaseDetailsRecipe
  completetime: 10
  categories:
  - MedievalDetailsCategory

## Пилорама

- type: latheRecipe
  parent: MedievalRawProcessingRecipe
  id: MedievalBoardRecipe
  result: MedievalBoard1
  completetime: 10
  materials:
    MedievalRawWood: 100

- type: latheRecipe
  parent: MedievalRawProcessingRecipe
  id: MedievalPartRodWoodRecipe
  result: MedievalPartRodWood3
  completetime: 30
  materials:
    MedievalRawWood: 100

## Стол плотника

- type: latheRecipe
  parent: MedievalBaseToolsRecipe
  id: MedievalBucketRecipe
  result: MedievalBucketRecipe
  materials:
    MedievalProcessedWood: 100

- type: latheRecipe
  parent: MedievalBaseDetailsRecipe
  id: MedievalCarpenterTableDetailRecipe
  result: MedievalCarpenterTableDetail
  materials:
    MedievalProcessedWood: 300

- type: latheRecipe
  parent: MedievalBaseDetailsRecipe
  id: MedievalAlchemTableDetailRecipe
  result: MedievalAlchemTableDetail
  materials:
    MedievalProcessedWood: 400

- type: latheRecipe
  parent: MedievalBaseDetailsRecipe
  id: MedievalReagentGrinderDetailRecipe
  result: MedievalReagentGrinderDetail
  materials:
    MedievalProcessedWood: 200

- type: latheRecipe
  parent: MedievalBaseDetailsRecipe
  id: MedievalHotplateDetailRecipe
  result: MedievalHotplateDetail
  materials:
    MedievalProcessedWood: 100

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodParquetRecipe
  result: MedievalFloorTileItemWoodParquet5

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodBlackRecipe
  result: MedievalFloorTileItemWoodBlack5

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodDarkRecipe
  result: MedievalFloorTileItemWoodDark5

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodLightRecipe
  result: MedievalFloorTileItemWoodLight5

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodRedRecipe
  result: MedievalFloorTileItemWoodRed5

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodLargeBlackRecipe
  result: MedievalFloorTileItemWoodLargeBlack5

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodLargeDarkRecipe
  result: MedievalFloorTileItemWoodLargeDark5

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodLargeLightRecipe
  result: MedievalFloorTileItemWoodLargeLight5

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodLargeRedRecipe
  result: MedievalFloorTileItemWoodLargeRed5

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodParquetBlackRecipe
  result: MedievalFloorTileItemWoodParquetBlack5

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodParquetDarkRecipe
  result: MedievalFloorTileItemWoodParquetDark5

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodParquetLightRecipe
  result: MedievalFloorTileItemWoodParquetLight5

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodParquetRedRecipe
  result: MedievalFloorTileItemWoodParquetRed5

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodChessRecipe
  result: MedievalFloorTileItemWoodChess5

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodChessBlackRecipe
  result: MedievalFloorTileItemWoodChessBlack5

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodChessDarkRecipe
  result: MedievalFloorTileItemWoodChessDark5

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodChessLightRecipe
  result: MedievalFloorTileItemWoodChessLight5

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodChessRedRecipe
  result: MedievalFloorTileItemWoodChessRed5

## Плавильня

- type: latheRecipe
  parent: MedievalRawProcessingRecipe
  id: MedievalIronIngotRecipe
  result: MedievalIronIngot1
  materials:
    MedievalRawIron: 200
    MedievalRawCoal: 100

- type: latheRecipe
  parent: MedievalRawProcessingRecipe
  id: MedievalSteelIngotRecipe
  result: MedievalSteelIngot1
  materials:
    MedievalRawIron: 300
    MedievalRawCoal: 100

- type: latheRecipe
  parent: MedievalRawProcessingRecipe
  id: MedievalSilverIngotRecipe
  result: MedievalSilverIngot1
  materials:
    MedievalRawSilver: 500
    MedievalRawCoal: 100

- type: latheRecipe
  parent: MedievalRawProcessingRecipe
  id: MedievalGoldIngotRecipe
  result: MedievalGoldIngot1
  materials:
    MedievalRawGold: 500
    MedievalRawCoal: 100

- type: latheRecipe
  parent: MedievalRawProcessingRecipe
  id: MedievalMithrilIngotRecipe
  result: MedievalMithrilIngot1
  materials:
    MedievalRawMithril: 300
    MedievalRawCoal: 100

- type: latheRecipe
  parent: MedievalRawProcessingRecipe
  id: MedievalAdamantineIngotRecipe
  result: MedievalAdamantineIngot1
  materials:
    MedievalRawAdamantine: 300
    MedievalRawCoal: 100

# Кузня

- type: latheRecipe
  parent: MedievalBaseDetailsRecipe
  id: MedievalSawmillDetailRecipe
  result: MedievalSawmillDetail
  materials:
    MedievalProcessedIron: 100

- type: latheRecipe
  parent: MedievalBaseToolsRecipe
  id: MedievalConstructionToolsRecipe
  result: MedievalConstructionTools
  materials:
    MedievalProcessedIron: 100
    MedievalProcessedWood: 100

# Каменоломня

- type: latheRecipe
  parent: MedievalBaseDetailsRecipe
  id: MedievalSmelterDetailRecipe
  result: MedievalSmelterDetail
  materials:
    MedievalProcessedStone: 300

# Общее

- type: latheRecipe
  parent: MedievalMaterialProcessingRecipe
  id: MedievaHammerAmmoRecipe
  result: MedievaConstructionToolsAmmo
  materials:
    MedievalProcessedWood: 100
    MedievalProcessedStone: 200
    MedievalProcessedIron: 100
