# Base
- type: latheRecipe
  abstract: true
  id: MedievalBaseSawmillRecipe
  categories:
  - MedievalWoodProcessing
  completetime: 10

- type: latheRecipe
  abstract: true
  id: MedievalBaseToolsRecipe
  completetime: 10
  categories:
  - MedievalWoodProcessing

- type: latheRecipe
  abstract: true
  id: MedievalBaseTileRecipe
  completetime: 10
  materials:
    MedievalProcessedWood: 300
  categories:
  - MedievalTile

- type: latheRecipe
  abstract: true
  id: MedievalBaseSmelter
  completetime: 10
  categories:
  - MedievalBlacksmithing

## Total Sawmill
- type: latheRecipe
  parent: MedievalBaseSawmillRecipe
  id: MedievalBoard
  result: MedievalBoard1
  completetime: 10
  materials:
    MedievalRawWood: 1000

## Total Carpenter Table
- type: latheRecipe
  parent: MedievalBaseToolsRecipe
  id: MedievalBucket
  result: MedievalBucket
  completetime: 10
  materials:
    MedievalProcessedWood: 1000

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodParquet
  result: MedievalFloorTileItemWoodParquet

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodBlack
  result: MedievalFloorTileItemWoodBlack

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodDark
  result: MedievalFloorTileItemWoodDark

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodLight
  result: MedievalFloorTileItemWoodLight

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodRed
  result: MedievalFloorTileItemWoodRed

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodLargeBlack
  result: MedievalFloorTileItemWoodLargeBlack

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodLargeDark
  result: MedievalFloorTileItemWoodLargeDark

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodLargeLight
  result: MedievalFloorTileItemWoodLargeLight

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodLargeRed
  result: MedievalFloorTileItemWoodLargeRed

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodParquetBlack
  result: MedievalFloorTileItemWoodParquetBlack

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodParquetDark
  result: MedievalFloorTileItemWoodParquetDark

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodParquetLight
  result: MedievalFloorTileItemWoodParquetLight

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodParquetRed
  result: MedievalFloorTileItemWoodParquetRed

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodChess
  result: MedievalFloorTileItemWoodChess

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodChessBlack
  result: MedievalFloorTileItemWoodChessBlack

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodChessDark
  result: MedievalFloorTileItemWoodChessDark

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodChessLight
  result: MedievalFloorTileItemWoodChessLight

- type: latheRecipe
  parent: MedievalBaseTileRecipe
  id: MedievalFloorTileItemWoodChessRed
  result: MedievalFloorTileItemWoodChessRed

## Total Smelter
- type: latheRecipe
  parent: MedievalBaseSmelter
  id: MedievalIronIngot
  result: MedievalIronIngot1
  completetime: 10
  materials:
    MedievalRawIron: 1000
    MedievalRawCoal: 1000

- type: latheRecipe
  parent: MedievalBaseSmelter
  id: MedievalSteelIngot
  result: MedievalSteelIngot1
  completetime: 10
  materials:
    MedievalRawIron: 2000
    MedievalRawCoal: 1000

- type: latheRecipe
  parent: MedievalBaseSmelter
  id: MedievalSilverIngot
  result: MedievalSilverIngot1
  completetime: 10
  materials:
    MedievalRawSilver: 1000
    MedievalRawCoal: 1000

- type: latheRecipe
  parent: MedievalBaseSmelter
  id: MedievalGoldIngot
  result: MedievalGoldIngot1
  completetime: 10
  materials:
    MedievalRawGold: 1000
    MedievalRawCoal: 1000

- type: latheRecipe
  parent: MedievalBaseSmelter
  id: MedievalMithrilIngot
  result: MedievalMithrilIngot1
  completetime: 10
  materials:
    MedievalRawMithril: 1000
    MedievalRawCoal: 1000

- type: latheRecipe
  parent: MedievalBaseSmelter
  id: MedievalAdamantineIngot
  result: MedievalAdamantineIngot1
  completetime: 10
  materials:
    MedievalRawAdamantine: 1000
    MedievalRawCoal: 1000
