- type: entity
  name: яблоко
  parent: FoodProduceBase
  id: FoodMedievalApple
  description: Сочное и сладкое яблоко, символ изобилия.
  components:
  - type: FlavorProfile
    flavors:
      - apple
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 10
        reagents:
        - ReagentId: Nutriment
          Quantity: 3
        - ReagentId: Vitamin
          Quantity: 2
  - type: Sprite
    sprite: _DeadSpace/_Medieval/Objects/Materials/Seeds/apple.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: MedievalApple
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: капуста
  parent: FoodProduceBase
  id: FoodMedievalCabbage
  description: Круглый кочан капусты, полезный и хрустящий.
  components:
  - type: FlavorProfile
    flavors:
      - cabbage
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 12
        reagents:
        - ReagentId: Nutriment
          Quantity: 5
  - type: Sprite
    sprite: _DeadSpace/_Medieval/Objects/Materials/Seeds/cabbage.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: MedievalCabbage
  - type: Tag
    tags:
    - Vegetable

- type: entity
  name: ягоды
  parent: FoodProduceBase
  id: FoodMedievalBerries
  description: Горсть лесных ягод, сладких и ароматных.
  components:
  - type: FlavorProfile
    flavors:
      - berry
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 10
        reagents:
        - ReagentId: Sugar
          Quantity: 5
        - ReagentId: Nutriment
          Quantity: 2
  - type: Sprite
    sprite: _DeadSpace/_Medieval/Objects/Materials/Seeds/berries.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: MedievalBerries
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: морковь
  parent: FoodProduceBase
  id: FoodMedievalCarrot
  description: Ярко-оранжевая морковь, полезна для глаз.
  components:
  - type: FlavorProfile
    flavors:
      - carrot
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 10
        reagents:
        - ReagentId: JuiceCarrot
          Quantity: 4
        - ReagentId: Vitamin
          Quantity: 2
  - type: Sprite
    sprite: _DeadSpace/_Medieval/Objects/Materials/Seeds/carrot.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: MedievalCarrot
  - type: Tag
    tags:
    - Vegetable

- type: entity
  name: вишня
  parent: FoodProduceBase
  id: FoodMedievalCherry
  description: Кисло-сладкая вишня, любимое лакомство летом.
  components:
  - type: FlavorProfile
    flavors:
      - cherry
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 10
        reagents:
        - ReagentId: Nutriment
          Quantity: 2
        - ReagentId: Sugar
          Quantity: 4
  - type: Sprite
    sprite: _DeadSpace/_Medieval/Objects/Materials/Seeds/cherry.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: MedievalCherry
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: лён
  parent: FoodProduceBase
  id: FoodMedievalFlax
  description: Стебель льна, из которого можно сделать нить.
  components:
  - type: FlavorProfile
    flavors:
      - cotton
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 8
        reagents:
        - ReagentId: Fiber
          Quantity: 4
  - type: Sprite
    sprite: _DeadSpace/_Medieval/Objects/Materials/Seeds/flax.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: MedievalFlax
  - type: Tag
    tags:
    - MedievalFlax

- type: entity
  name: картошка
  parent: FoodProduceBase
  id: FoodMedievalPotato
  description: Сытный клубень картофеля, основа крестьянского стола.
  components:
  - type: FlavorProfile
    flavors:
      - potato
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 12
        reagents:
        - ReagentId: Nutriment
          Quantity: 4
  - type: Sprite
    sprite: _DeadSpace/_Medieval/Objects/Materials/Seeds/potato.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: MedievalPotato
  - type: Tag
    tags:
    - Vegetable

- type: entity
  name: помидор
  parent: FoodProduceBase
  id: FoodMedievalTomato
  description: Сочный красный помидор, хорош как свежим, так и в рагу.
  components:
  - type: FlavorProfile
    flavors:
      - tomato
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 10
        reagents:
        - ReagentId: Nutriment
          Quantity: 3
        - ReagentId: Vitamin
          Quantity: 1
  - type: Sprite
    sprite: _DeadSpace/_Medieval/Objects/Materials/Seeds/tomato.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: MedievalTomato
  - type: Tag
    tags:
    - Vegetable

- type: entity
  name: пшеница
  parent: FoodProduceBase
  id: FoodMedievalWheat
  description: Золотистые колосья пшеницы, источник муки и хлеба.
  components:
  - type: FlavorProfile
    flavors:
      - wheat
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 10
        reagents:
        - ReagentId: Flour
          Quantity: 5
  - type: Sprite
    sprite: _DeadSpace/_Medieval/Objects/Materials/Seeds/wheat.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: MedievalWheat
  - type: Tag
    tags:
    - Wheat
