- type: entity
  id: MedievalSawmillDetail
  parent: MedievalBaseMachineDetail
  name: деталь пилорамы
  components:
  - type: MachineBoard
    prototype: MedievalSawmill
    stackRequirements: # Пока так
      MatterBin: 1
      Manipulator: 3
      Glass: 1

- type: entity
  id: MedievalCarpenterTableDetail
  parent: MedievalBaseMachineDetail
  name: деталь стола плотника
  components:
  - type: MachineBoard
    prototype: MedievalCarpenterTable
    stackRequirements: # Пока так
      MatterBin: 1
      Manipulator: 3
      Glass: 1

- type: entity
  id: MedievalSmelterDetail
  parent: MedievalBaseMachineDetail
  name: деталь плавильни
  components:
  - type: MachineBoard
    prototype: MedievalSmelter
    stackRequirements: # Пока так
      MatterBin: 1
      Manipulator: 3
      Glass: 1

- type: entity
  id: MedievalAlchemTableDetail
  parent: MedievalBaseMachineDetail
  name: деталь алхимического стола
  components:
  - type: MachineBoard
    prototype: MedievalAlchemTable
    stackRequirements: # Пока так
      MatterBin: 1
      Manipulator: 3
      Glass: 1

- type: entity
  id: MedievalReagentGrinderDetail
  parent: MedievalBaseMachineDetail
  name: деталь алхимического стола
  components:
  - type: MachineBoard
    prototype: MedievalReagentGrinder
    stackRequirements: # Пока так
      MatterBin: 1
      Manipulator: 3
      Glass: 1

- type: entity
  id: MedievalHotplateDetail
  parent: MedievalBaseMachineDetail
  name: деталь костровой жаровни
  components:
  - type: MachineBoard
    prototype: MedievalHotplate
    stackRequirements: # Пока так
      MatterBin: 1
      Manipulator: 3
      Glass: 1
