- type: entity
  name: бревно
  description: Тяжелая, отрубленная часть дерева. В одной руке его утащит разве-что гигант.
  id: MedievalLog
  categories: [ HideSpawnMenu ]
  parent: MedievalRawMaterialBase
  components:
  - type: Stack
    stackType: MedievalRawWood
  - type: Sprite
    sprite: _DeadSpace/_Medieval/Objects/Materials/log.rsi
    state: log
  - type: Item
    sprite: _DeadSpace/_Medieval/Objects/Materials/log.rsi
    size: Huge
    heldPrefix: log
  - type: MeleeWeapon
    attackRate: 0.5
    damage:
      types:
        Blunt: 10
  - type: Tag
    tags:
    - MedievalSawmillMaterialStorage
  - type: MultiHandedItem
  - type: Produce
    seedId: towercap
  - type: PhysicalComposition
    materialComposition:
      MedievalRawWood: 1000

- type: entity
  id: MedievalLog1
  parent: MedievalLog
  components:
  - type: Stack
    count: 1

- type: entity
  parent: MedievalOreBase
  id: MedievalStoneOre
  categories: [ HideSpawnMenu ]
  name: каменная руда
  components:
  - type: Stack
    stackType: MedievalRawStone
  - type: Sprite
    layers:
    - state: stone
      map: ["random"]
  - type: PhysicalComposition
    materialComposition:
      MedievalRawStone: 1000
  - type: Item
    inhandVisuals:
      left:
      - state: stone-inhand-left
      right:
      - state: stone-inhand-right
  - type: RandomSprite
    available:
    - random:
        stone: ""
        stone2: ""
        stone3: ""

- type: entity
  id: MedievalStoneOre1
  parent: MedievalStoneOre
  components:
  - type: Stack
    count: 1

- type: entity
  parent: MedievalOreBase
  id: MedievalCoalOre
  categories: [ HideSpawnMenu ]
  name: угольная руда
  components:
  - type: Stack
    stackType: MedievalRawCoal
  - type: Tag
    tags:
    - MedievalSmelterMaterialStorage
  - type: Sprite
    layers:
    - state: coal
      map: ["random"]
  - type: PhysicalComposition
    materialComposition:
      MedievalRawCoal: 1000
  - type: Item
    inhandVisuals:
      left:
      - state: coal-inhand-left
      right:
      - state: coal-inhand-right
  - type: RandomSprite
    available:
    - random:
        coal: ""
        coal2: ""
        coal3: ""

- type: entity
  id: MedievalCoalOre1
  parent: MedievalCoalOre
  components:
  - type: Stack
    count: 1

- type: entity
  parent: MedievalOreBase
  id: MedievalIronOre
  categories: [ HideSpawnMenu ]
  name: железная руда
  components:
  - type: Stack
    stackType: MedievalRawIron
  - type: Tag
    tags:
    - MedievalSmelterMaterialStorage
  - type: Sprite
    layers:
    - state: iron
      map: ["random"]
  - type: PhysicalComposition
    materialComposition:
      MedievalRawIron: 1000
  - type: Item
    inhandVisuals:
      left:
      - state: iron-inhand-left
      right:
      - state: iron-inhand-right
  - type: RandomSprite
    available:
    - random:
        iron: ""
        iron2: ""
        iron3: ""

- type: entity
  id: MedievalIronOre1
  parent: MedievalIronOre
  components:
  - type: Stack
    count: 1

- type: entity
  parent: MedievalOreBase
  id: MedievalSilverOre
  categories: [ HideSpawnMenu ]
  name: серебряная руда
  components:
  - type: Stack
    stackType: MedievalRawSilver
  - type: Tag
    tags:
    - MedievalSmelterMaterialStorage
  - type: Sprite
    layers:
    - state: silver
      map: ["random"]
  - type: PhysicalComposition
    materialComposition:
      MedievalRawSilver: 1000
  - type: Item
    inhandVisuals:
      left:
      - state: silver-inhand-left
      right:
      - state: silver-inhand-right
  - type: RandomSprite
    available:
    - random:
        silver: ""
        silver2: ""
        silver3: ""

- type: entity
  id: MedievalSilverOre1
  parent: MedievalSilverOre
  components:
  - type: Stack
    count: 1

- type: entity
  parent: MedievalOreBase
  id: MedievalGoldOre
  categories: [ HideSpawnMenu ]
  name: золотая руда
  components:
  - type: Stack
    stackType: MedievalRawGold
  - type: Tag
    tags:
    - MedievalSmelterMaterialStorage
  - type: Sprite
    layers:
    - state: gold
      map: ["random"]
  - type: PhysicalComposition
    materialComposition:
      MedievalRawGold: 1000
  - type: Item
    inhandVisuals:
      left:
      - state: gold-inhand-left
      right:
      - state: gold-inhand-right
  - type: RandomSprite
    available:
    - random:
        gold: ""
        gold2: ""
        gold3: ""

- type: entity
  id: MedievalGoldOre1
  parent: MedievalGoldOre
  components:
  - type: Stack
    count: 1

- type: entity
  parent: MedievalOreBase
  id: MedievalMithrilOre
  categories: [ HideSpawnMenu ]
  name: мифриловая руда
  components:
  - type: Stack
    stackType: MedievalRawMithril
  - type: Tag
    tags:
    - MedievalSmelterMaterialStorage
  - type: Sprite
    layers:
    - state: mithril
      map: ["random"]
  - type: PhysicalComposition
    materialComposition:
      MedievalRawMithril: 1000
  - type: Item
    inhandVisuals:
      left:
      - state: mithril-inhand-left
      right:
      - state: mithril-inhand-right

- type: entity
  id: MedievalMithrilOre1
  parent: MedievalMithrilOre
  components:
  - type: Stack
    count: 1

- type: entity
  parent: MedievalOreBase
  id: MedievalAdamantineOre
  categories: [ HideSpawnMenu ]
  name: адамантитовая руда
  components:
  - type: Stack
    stackType: MedievalRawAdamantine
  - type: Tag
    tags:
    - MedievalSmelterMaterialStorage
  - type: Sprite
    layers:
    - state: adamantine
      map: ["random"]
  - type: PhysicalComposition
    materialComposition:
      MedievalRawAdamantine: 1000
  - type: Item
    inhandVisuals:
      left:
      - state: adamantine-inhand-left
      right:
      - state: adamantine-inhand-right

- type: entity
  id: MedievalAdamantineOre1
  parent: MedievalAdamantineOre
  components:
  - type: Stack
    count: 1

- type: entity
  parent: MedievalCrystalBase
  id: MedievalManaCrystal
  categories: [ HideSpawnMenu ]
  name: кристал маны
  components:
  - type: Stack
    stackType: MedievalManaCrystal
  - type: Sprite
    layers:
    - state: mana
      map: ["base"]
  - type: PhysicalComposition
    materialComposition:
      MedievalRawManaCrystal: 1000
  - type: PointLight
    radius: 2
    energy: 2.5
    color: "#47f8ff"
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 5
        reagents:
        - ReagentId: MedievalMana
          Quantity: 5
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: MedievalMana
        Quantity: 5

- type: entity
  id: MedievalManaCrystal1
  parent: MedievalManaCrystal
  components:
  - type: Stack
    count: 1
